### ISSUE TITLE
Integrating existing / "legacy" neo4j  database (like inspectdb)?

### ISSUE THREAD

**Issue by mendter** [robinedwards/django-neomodel#11]
Hello django-neomodel-team,

I need to integrate an **existing** neo4j-database into my django project using your package. Is there any best practice or things I need to consider to do this?

For relational databases django provides the **inspectdb** command. Is there an equivalent for django-neomodel?

Thank you very much!
Maximilian Endter

**Comment by adriancarayol** [comment]
Hi mendter, I think that inspectdb for django-neomodel is not yet available.
